version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - whalo-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - whalo-network

  player:
    build:
      context: .
      dockerfile: player.ms/Dockerfile
    container_name: player
    environment:
      MONGODB_URI: mongodb://admin:password@mongo:27017/whalo-players?authSource=admin
    ports:
      - "3001:3001"
    working_dir: /app
    depends_on:
      - mongo
    networks:
      - whalo-network

  score:
    build:
      context: .
      dockerfile: score.ms/Dockerfile
    environment:
      MONGODB_URI: mongodb://admin:password@mongo:27017/whalo-scores?authSource=admin
      REDIS_URL: redis://redis:6379
      PLAYER_URL: http://player:3001/api/player
    ports:
      - "3002:3002"
    depends_on:
      - redis
      - mongo
      - rabbitmq
    networks:
      - whalo-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - whalo-network

networks:
  whalo-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  rabbitmq-data:



  # player:
    # build:
    #   context: ./player.ms
    #   dockerfile: Dockerfile
    # environment:
    #   MONGODB_URI: mongodb://admin:password@mongo:27017/whalo?authSource=admin
    #   REDIS_URL: redis://redis:6379
    # ports:
    #   - "3001:3001"
    # depends_on:
    #   - redis
    #   - mongo
    # networks:
    #   - whalo-network